#!/usr/bin/env python	
import PyOpenColorIO as OCIO
import sys
import os
import bundlemakerclass.beputils as bepUtils
img=sys.argv[1]
config = OCIO.GetCurrentConfig()
colorSpaceNames = [ cs.getName() for cs in config.getColorSpaces() ]
color=None
for cs in colorSpaceNames:
    if img.find(cs)>-1:
        color=cs
 
if color: print color
else :
    levelSolver=bepUtils.solveLevelConfig()
    defaultCSFile=levelSolver.getDefaultFile('tools','config/defaultColorSpaces.py')
    global defaultColorSpaces
    execfile(defaultCSFile)
    ext=os.path.splitext(img)[1][1:]
    if ext in defaultColorSpaces.keys():
        print defaultColorSpaces[ext]
    else : print ""


    