project = hiero.ui.activeSequence().project()
sequences = project.sequences()
sequenceName = hiero.ui.activeSequence()
sequenceTracks = sequenceName.items()
for track in sequenceTracks:
    print track.name()
    trackItems = track.items()
    # Handle SubTrackItems on Video Tracks
    for items in trackItems:
        TrackItemClip= items.source()
        print items.name()
        print TrackItemClip
        clipMediaSource = TrackItemClip.mediaSource()
        mediaSourceMetaData = clipMediaSource.metadata()
        print mediaSourceMetaData.value("foundry.source.path")

        fullPath = mediaSourceMetaData.value("foundry.source.path")

        filename, file_extension = os.path.splitext(fullPath)

        print file_extension

        if file_extension == '.nk' :
            nuke.scriptOpen(fullPath)

            newExtension = '.jpg'

            n = nuke.allNodes()

            for i in n:
                if i.Class() == "Write":
                    i.knob("selected").setValue(True)
                    testReplace=i.knob("file").getValue()

                    print 'Before Replace: ', testReplace
                    testReplace = os.path.splitext(testReplace)[0]+ newExtension
                    print 'After Replace: ', testReplace
                    i.knob("file").setValue(testReplace)

            nuke.scriptSave("")
            nuke.scriptClose()


viewer_fg_color_3D
UIRotoLineWidth
NodeColour07Color
DopeSheetSelectedKey
UIDiskCacheFrameColor
dot_node_scale
pause_caching_in_background
SelectedLabelColor
TimelineDiskCachePath
selectedGPUDeviceName
UISplineWarperBoundaryColor
SelectedPanelBGColor
NodeColourClass04
stringLiteralsFgColourDQ
LocalizationUpdateNever
useLayoutFromScript
defaultGPUForInputs
autokillViewer
postage_stamp_mode
TileWidth
documentationServerPortLocal
SelectedInputLabelColor
expression_arrows
CacheLimit
PanelInputButtonLogic
maxChannels
Viewer3DControlEmulation
commentsFgColour
PanelWrapMoreWidgets
UIAnimatedColor
colorset
ShadeDAGNodes
DopeSheetControlText
InputArrowSize
viewer_handle_pick_size
DraggableArrowHeads
PanelShowInputButtons
clone_arrows
LeftInputArrowSize
UISplineWarperBSourceColor
DopeSheetTimeLabel
GridWidth
PanelBGColor
AutoColors
object_interaction_speed
pathRemaps
UIRotoCurveColor
DfltBezAutokey
UISplineWarperSrcStippled
undoMin
UIRotoDrawShadow
selectedGPUDeviceNum
LabelSize
TileHeight
UISplineWarperADestColor
UISplineWarperCorrespondenceColor
suppressBadChannels
NodeColour11Color
name
maxPanels
RestrictArrowHotspotToMidpoint
DopeSheetUnselectedKey
UIRotoPointColor
scriptEditorClearOnSuccess
NodeColourClassDeep
show_transform_preview
useTMIPicker
viewer_grid_color
AutoSaveTime
UIKeyframeColor
NodeColourClass11
NodeColour08Color
ArrowColorUp
TextureSize
preserve_caches
ScriptEditorFont
NodeColourClass09
kwdsFgColour
LocalizationPauseOnProjectLoad
Choose
defaultBufferDepth
colorPickerDefaultMode
default_no_incomplete_stereo
ArrowColor
UIHighlightedTextColor
UISplineWarperBDestColor
LabelColor
SnapToNode
NodeColourDeepColor
DopeSheetControlTextShadow
UIFrameSliderHeadColor
UIButtonColor
documentationServerHostFoundry
TimelineDiskCacheLimit
NodeColour04Color
RAMCacheFrameColor
camera_interaction_speed
UILabelColor
expression_arrow_color
openMovesPanel
UISplineExpressionColor
documentationServerPortLocalRange
clr_desc_12
UIRotoTransformJackColor
UIFont
useLastSavedDir
viewer_handle_pick_size_3d
node_name_bg_blend
middleButtonPans
PanelNodeColorMix
UISplineWarperCutoutColour
goofy_foot
selectedGPUDeviceIndex
UseNewRotationControls
DfltAbcAlwaysCreateAllInOne
documentationServerPortFoundry
DefaultNodeGLColor
UISplineFocusColor
autocolor
animationOnTop
echoAllCommands
scopesBlackpoint
SnapThreshold
icon_size_power
clr_desc_09
showPanelsOnLoad
UIBackColor
clr_desc_05
clr_desc_04
clr_desc_07
clr_desc_06
clr_desc_01
ViewerPopupClasses
clr_desc_03
FloatingWindowHint
clear_cache_in_background
clr_value_08
clr_value_09
LocalizationSizeLimit
clr_value_02
clr_value_03
clr_value_01
clr_value_06
sizePanelsOnLoad
clr_value_04
clr_value_05
MaxPanelsOpenedAtOnce
autoLocalCachePath
DopeSheetPartSelectedKey
UIRotoLockedColor
platformPathRemaps
autolabel
OutputArrowSize
PanelNewWindowPerPanel
TooltipsEnabled
PaintCacheGB
LocalizationPolicyDefault
viewer_world_coordinate_system
NodeColourClass12
PanelWidgetBoxes
ctrlOnTop
icon_size_base
PanelShowCenterButton
scopesForceFullFrame
enableMultiGPU
show_grid
viewer_flip_stereo_interlaced_views
SnapFarWindows
NodeColourClass08
clr_desc_10
clr_desc_11
UIFrameSliderInOutColor
NodeColour12Color
NodeColourClass01
NodeColourClass03
NodeColourClass02
NodeColourClass05
ClearWindowPositions
NodeColourClass07
NodeColourClass06
PanelCloseWindowWhenEmpty
UseArrowElbows
UISplineWarperASourceColor
clr_value_11
clr_value_10
localCachePath
groupOnTop
UISequenceDisplayMode
defaultDisableGPUDither
NodeColour02Color
ExpandSelection
CollapseMenuBars
NodeColour03Color
SelectedColor
DopeSheetFrameRange
AlwaysMovePanelToEdge
OverlayColor
showMultiGPU
clr_value_12
ShowDialogsUnderCursor
ScriptEditorFontSize
SnapWindows
UISplineWarperDstStippled
NodeColourClassCache
AlreadyQueuedItemColor
scopesWhitepoint
UISplineWarperDestColor
viewer_bg_color
NodeColour13Color
stringLiteralsFgColourSQ
clr_desc_08
dag_snap_threshold
ArrowheadLength
NodeColourCacheColor
DopeSheetCurrentFrame
diskCacheGB
MaxVisibleCurves
NodeColourClass13
NodeColourClass10
NodeColour01Color
viewer_handle_size
PanelFixedSize
Script_command_default
AutoSaveIdle
TooltipDelay
RenderWithFrameServer
NodeColour10Color
SelectedPanelNodeColorMix
undoLimitMB
UIFontSize
PlaybackLimit
AutoSaveName
newViewersGoToOwnWindow
CollapseGroupMenuBars
ArrowColorDown
documentationServerHostCustom
moveReopened
ArrowWidth
ShowMenusUnderCursor
ArrowColorLeft
UseWindowLayouts
documentationServer
trialOFXPlugins
clr_desc_02
viewer_bg_color_3D
documentationServerPortCustom
ShowRunning
viewer_sel_color_3D
ArrowColorElbow
viewer_texture_mode
PaintCacheLimit
MonitorOutUseLegalRange
NodeColour09Color
GridHeight
defaultGPUForViewer
clone_arrow_color
avoid_hiding
viewer_handle_size_3d
UISplineWarperSourceColor
viewerOnTop
reopenMovesPanel
defaultFreezeGuiWhenPlayBack
UIBaseColor
QuickTimeReaderLimit
SelectionHoverColor
DAGBackColor
leftMiddleZooms
NodeColour06Color
DiskCachePath
NewPanelsOnBottom
NodeColour05Color
viewer_texture_vram
LabelFont
ArrowheadWidth
UICacheframeColor
default_zoom_lock
DopeSheetTimeline
UIAssumeZeroPadding
LocalizationUpdatePeriodMinutes
NodeColor
SnapToGrid
documentationServerPortLocalAuto
scopesApplyViewerColorTransform
UIHighlightColor
clr_value_07
old_icons
rgb_only
viewer_fg_color
newPanelsInBin
DopeSheetBackground
ArrowColorRight
node = nuke.toNode('viewer')

for i in node.knobs():
    print i
# Result: Traceback (most recent call last):
  File "<string>", line 3, in <module>
AttributeError: 'NoneType' object has no attribute 'knobs'
node = nuke.toNode('preferences')

for i in node.knobs():
    print i
# Result: viewer_fg_color_3D
UIRotoLineWidth
NodeColour07Color
DopeSheetSelectedKey
UIDiskCacheFrameColor
dot_node_scale
pause_caching_in_background
SelectedLabelColor
TimelineDiskCachePath
selectedGPUDeviceName
UISplineWarperBoundaryColor
SelectedPanelBGColor
NodeColourClass04
stringLiteralsFgColourDQ
LocalizationUpdateNever
useLayoutFromScript
defaultGPUForInputs
autokillViewer
postage_stamp_mode
TileWidth
documentationServerPortLocal
SelectedInputLabelColor
expression_arrows
CacheLimit
PanelInputButtonLogic
maxChannels
Viewer3DControlEmulation
commentsFgColour
PanelWrapMoreWidgets
UIAnimatedColor
colorset
ShadeDAGNodes
DopeSheetControlText
InputArrowSize
viewer_handle_pick_size
DraggableArrowHeads
PanelShowInputButtons
clone_arrows
LeftInputArrowSize
UISplineWarperBSourceColor
DopeSheetTimeLabel
GridWidth
PanelBGColor
AutoColors
object_interaction_speed
pathRemaps
UIRotoCurveColor
DfltBezAutokey
UISplineWarperSrcStippled
undoMin
UIRotoDrawShadow
selectedGPUDeviceNum
LabelSize
TileHeight
UISplineWarperADestColor
UISplineWarperCorrespondenceColor
suppressBadChannels
NodeColour11Color
name
maxPanels
RestrictArrowHotspotToMidpoint
DopeSheetUnselectedKey
UIRotoPointColor
scriptEditorClearOnSuccess
NodeColourClassDeep
show_transform_preview
useTMIPicker
viewer_grid_color
AutoSaveTime
UIKeyframeColor
NodeColourClass11
NodeColour08Color
ArrowColorUp
TextureSize
preserve_caches
ScriptEditorFont
NodeColourClass09
kwdsFgColour
LocalizationPauseOnProjectLoad
Choose
defaultBufferDepth
colorPickerDefaultMode
default_no_incomplete_stereo
ArrowColor
UIHighlightedTextColor
UISplineWarperBDestColor
LabelColor
SnapToNode
NodeColourDeepColor
DopeSheetControlTextShadow
UIFrameSliderHeadColor
UIButtonColor
documentationServerHostFoundry
TimelineDiskCacheLimit
NodeColour04Color
RAMCacheFrameColor
camera_interaction_speed
UILabelColor
expression_arrow_color
openMovesPanel
UISplineExpressionColor
documentationServerPortLocalRange
clr_desc_12
UIRotoTransformJackColor
UIFont
useLastSavedDir
viewer_handle_pick_size_3d
node_name_bg_blend
middleButtonPans
PanelNodeColorMix
UISplineWarperCutoutColour
goofy_foot
selectedGPUDeviceIndex
UseNewRotationControls
DfltAbcAlwaysCreateAllInOne
documentationServerPortFoundry
DefaultNodeGLColor
UISplineFocusColor
autocolor
animationOnTop
echoAllCommands
scopesBlackpoint
SnapThreshold
icon_size_power
clr_desc_09
showPanelsOnLoad
UIBackColor
clr_desc_05
clr_desc_04
clr_desc_07
clr_desc_06
clr_desc_01
ViewerPopupClasses
clr_desc_03
FloatingWindowHint
clear_cache_in_background
clr_value_08
clr_value_09
LocalizationSizeLimit
clr_value_02
clr_value_03
clr_value_01
clr_value_06
sizePanelsOnLoad
clr_value_04
clr_value_05
MaxPanelsOpenedAtOnce
autoLocalCachePath
DopeSheetPartSelectedKey
UIRotoLockedColor
platformPathRemaps
autolabel
OutputArrowSize
PanelNewWindowPerPanel
TooltipsEnabled
PaintCacheGB
LocalizationPolicyDefault
viewer_world_coordinate_system
NodeColourClass12
PanelWidgetBoxes
ctrlOnTop
icon_size_base
PanelShowCenterButton
scopesForceFullFrame
enableMultiGPU
show_grid
viewer_flip_stereo_interlaced_views
SnapFarWindows
NodeColourClass08
clr_desc_10
clr_desc_11
UIFrameSliderInOutColor
NodeColour12Color
NodeColourClass01
NodeColourClass03
NodeColourClass02
NodeColourClass05
ClearWindowPositions
NodeColourClass07
NodeColourClass06
PanelCloseWindowWhenEmpty
UseArrowElbows
UISplineWarperASourceColor
clr_value_11
clr_value_10
localCachePath
groupOnTop
UISequenceDisplayMode
defaultDisableGPUDither
NodeColour02Color
ExpandSelection
CollapseMenuBars
NodeColour03Color
SelectedColor
DopeSheetFrameRange
AlwaysMovePanelToEdge
OverlayColor
showMultiGPU
clr_value_12
ShowDialogsUnderCursor
ScriptEditorFontSize
SnapWindows
UISplineWarperDstStippled
NodeColourClassCache
AlreadyQueuedItemColor
scopesWhitepoint
UISplineWarperDestColor
viewer_bg_color
NodeColour13Color
stringLiteralsFgColourSQ
clr_desc_08
dag_snap_threshold
ArrowheadLength
NodeColourCacheColor
DopeSheetCurrentFrame
diskCacheGB
MaxVisibleCurves
NodeColourClass13
NodeColourClass10
NodeColour01Color
viewer_handle_size
PanelFixedSize
Script_command_default
AutoSaveIdle
TooltipDelay
RenderWithFrameServer
NodeColour10Color
SelectedPanelNodeColorMix
undoLimitMB
UIFontSize
PlaybackLimit
AutoSaveName
newViewersGoToOwnWindow
CollapseGroupMenuBars
ArrowColorDown
documentationServerHostCustom
moveReopened
ArrowWidth
ShowMenusUnderCursor
ArrowColorLeft
UseWindowLayouts
documentationServer
trialOFXPlugins
clr_desc_02
viewer_bg_color_3D
documentationServerPortCustom
ShowRunning
viewer_sel_color_3D
ArrowColorElbow
viewer_texture_mode
PaintCacheLimit
MonitorOutUseLegalRange
NodeColour09Color
GridHeight
defaultGPUForViewer
clone_arrow_color
avoid_hiding
viewer_handle_size_3d
UISplineWarperSourceColor
viewerOnTop
reopenMovesPanel
defaultFreezeGuiWhenPlayBack
UIBaseColor
QuickTimeReaderLimit
SelectionHoverColor
DAGBackColor
leftMiddleZooms
NodeColour06Color
DiskCachePath
NewPanelsOnBottom
NodeColour05Color
viewer_texture_vram
LabelFont
ArrowheadWidth
UICacheframeColor
default_zoom_lock
DopeSheetTimeline
UIAssumeZeroPadding
LocalizationUpdatePeriodMinutes
NodeColor
SnapToGrid
documentationServerPortLocalAuto
scopesApplyViewerColorTransform
UIHighlightColor
clr_value_07
old_icons
rgb_only
viewer_fg_color
newPanelsInBin
DopeSheetBackground
ArrowColorRight
